### ISSUE TITLE
How best to show current conditions?

### ISSUE THREAD

**Issue by dotis** [noaa-onms/climate-dashboard#4]
What is the best way to show current conditions? I was thinking of including a tab at the top. Can we use a set of guages showing a summary of data over the last 2/3 months? Ideally, this would show how things are with respect to "normal" conditions. Is the water really hot? Are CHLa levels really high? One issue is that at monthly time steps, "current conditions" can get stale quickly.

I am working on spinning up 1-km OC and SST data along the US east and west coasts for this (and other) purposes. These would be served via ERDDAP and I could also extract .csv files as I do each night for our current dashboards. The images and csv would be on daily and weekly time scales.

**Comment by 7yl4r** [comment]
We are talking about setting up two different "views" for the dashboard:

1. "current status" view
2. "all data" view

Rather than trying to combine them into one interface, we could create a separate dashboard page for each view.
